[package]
name = "bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
poise = "0.6.1"
tokio = {version = "1.36.0", features = ["full", "rt-multi-thread"]}
